/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "designs/spm/src/spm.v:1" *)
module spm(clk, rst, start, serial_mult, parallel_mult, product, done);
  (* src = "designs/spm/src/spm.v:15" *)
  wire _000_;
  (* src = "designs/spm/src/spm.v:15" *)
  wire [3:0] _001_;
  (* src = "designs/spm/src/spm.v:15" *)
  wire _002_;
  (* src = "designs/spm/src/spm.v:15" *)
  wire [15:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  (* src = "designs/spm/src/spm.v:13" *)
  reg active;
  (* src = "designs/spm/src/spm.v:2" *)
  input clk;
  (* src = "designs/spm/src/spm.v:12" *)
  reg [3:0] count;
  (* src = "designs/spm/src/spm.v:8" *)
  output done;
  reg done;
  (* src = "designs/spm/src/spm.v:6" *)
  input [7:0] parallel_mult;
  (* src = "designs/spm/src/spm.v:7" *)
  output [15:0] product;
  reg [15:0] product;
  (* src = "designs/spm/src/spm.v:3" *)
  input rst;
  (* src = "designs/spm/src/spm.v:5" *)
  input serial_mult;
  (* src = "designs/spm/src/spm.v:4" *)
  input start;
  assign _004_ = active ? product[1] : product[0];
  assign _003_[0] = _004_ & ~(start);
  assign _005_ = active ? product[2] : product[1];
  assign _003_[1] = _005_ & ~(start);
  assign _006_ = active ? product[3] : product[2];
  assign _003_[2] = _006_ & ~(start);
  assign _007_ = active ? product[4] : product[3];
  assign _003_[3] = _007_ & ~(start);
  assign _008_ = active ? product[5] : product[4];
  assign _003_[4] = _008_ & ~(start);
  assign _009_ = active ? product[6] : product[5];
  assign _003_[5] = _009_ & ~(start);
  assign _010_ = active ? product[7] : product[6];
  assign _003_[6] = _010_ & ~(start);
  assign _011_ = active ? product[8] : product[7];
  assign _003_[7] = _011_ & ~(start);
  assign _012_ = active ? product[9] : product[8];
  assign _003_[8] = _012_ & ~(start);
  assign _013_ = active ? product[10] : product[9];
  assign _003_[9] = _013_ & ~(start);
  assign _014_ = active ? product[11] : product[10];
  assign _003_[10] = _014_ & ~(start);
  assign _015_ = active ? product[12] : product[11];
  assign _003_[11] = _015_ & ~(start);
  assign _016_ = active ? product[13] : product[12];
  assign _003_[12] = _016_ & ~(start);
  assign _017_ = active ? product[14] : product[13];
  assign _003_[13] = _017_ & ~(start);
  assign _018_ = active ? product[15] : product[14];
  assign _003_[14] = _018_ & ~(start);
  assign _019_ = ~start;
  assign _020_ = active | ~(product[15]);
  assign _003_[15] = _019_ & ~(_020_);
  assign _021_ = ~(active ^ count[0]);
  assign _001_[0] = _019_ & ~(_021_);
  assign _022_ = ~count[1];
  assign _023_ = ~active;
  assign _024_ = ~(count[1] ^ count[0]);
  assign _025_ = active ? _024_ : _022_;
  assign _001_[1] = _019_ & ~(_025_);
  assign _026_ = ~count[2];
  assign _027_ = ~(count[1] & count[0]);
  assign _028_ = _027_ ^ count[2];
  assign _029_ = active ? _028_ : _026_;
  assign _001_[2] = _019_ & ~(_029_);
  assign _030_ = ~count[3];
  assign _031_ = count[2] & ~(_027_);
  assign _032_ = _031_ ^ _030_;
  assign _033_ = active ? _032_ : _030_;
  assign _001_[3] = _019_ & ~(_033_);
  assign _034_ = ~(count[1] | count[0]);
  assign _035_ = count[2] | ~(count[3]);
  assign _036_ = _034_ & ~(_035_);
  assign _037_ = ~((_036_ & active) | done);
  assign _002_ = _019_ & ~(_037_);
  assign _000_ = ~((_036_ | _023_) & _019_);
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      done <= 0;
    else
      done <= _002_;
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[0] <= 0;
    else
      count[0] <= _001_[0];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[1] <= 0;
    else
      count[1] <= _001_[1];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[2] <= 0;
    else
      count[2] <= _001_[2];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      count[3] <= 0;
    else
      count[3] <= _001_[3];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[0] <= 0;
    else
      product[0] <= _003_[0];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[1] <= 0;
    else
      product[1] <= _003_[1];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[2] <= 0;
    else
      product[2] <= _003_[2];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[3] <= 0;
    else
      product[3] <= _003_[3];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[4] <= 0;
    else
      product[4] <= _003_[4];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[5] <= 0;
    else
      product[5] <= _003_[5];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[6] <= 0;
    else
      product[6] <= _003_[6];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[7] <= 0;
    else
      product[7] <= _003_[7];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[8] <= 0;
    else
      product[8] <= _003_[8];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[9] <= 0;
    else
      product[9] <= _003_[9];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[10] <= 0;
    else
      product[10] <= _003_[10];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[11] <= 0;
    else
      product[11] <= _003_[11];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[12] <= 0;
    else
      product[12] <= _003_[12];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[13] <= 0;
    else
      product[13] <= _003_[13];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[14] <= 0;
    else
      product[14] <= _003_[14];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      product[15] <= 0;
    else
      product[15] <= _003_[15];
  (* src = "designs/spm/src/spm.v:15" *)
  always @(posedge clk or posedge rst)
    if (rst)
      active <= 0;
    else
      active <= _000_;
endmodule
