/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "designs/spm/src/spm.v:1" *)
module spm(clk, rst, start, serial_mult, parallel_mult, product, done);
  (* src = "designs/spm/src/spm.v:14" *)
  wire _000_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire [3:0] _001_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _002_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire [15:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _038_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _039_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _040_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _041_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _042_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _043_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _044_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _045_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _046_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _047_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _048_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _049_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _050_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _051_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _052_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _053_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _054_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _055_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _056_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _057_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _058_;
  (* src = "designs/spm/src/spm.v:14" *)
  wire _059_;
  (* src = "designs/spm/src/spm.v:12" *)
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  (* src = "designs/spm/src/spm.v:11" *)
  wire _083_;
  (* src = "designs/spm/src/spm.v:11" *)
  wire _084_;
  (* src = "designs/spm/src/spm.v:11" *)
  wire _085_;
  (* src = "designs/spm/src/spm.v:11" *)
  wire _086_;
  (* src = "designs/spm/src/spm.v:8" *)
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _112_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _113_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _114_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _115_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _116_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _117_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _118_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _119_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _120_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _121_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _122_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _123_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _124_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _125_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _126_;
  (* src = "designs/spm/src/spm.v:7" *)
  wire _127_;
  (* src = "designs/spm/src/spm.v:3" *)
  wire _128_;
  (* src = "designs/spm/src/spm.v:4" *)
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  (* src = "designs/spm/src/spm.v:12" *)
  wire active;
  (* src = "designs/spm/src/spm.v:2" *)
  input clk;
  (* src = "designs/spm/src/spm.v:11" *)
  wire [3:0] count;
  (* src = "designs/spm/src/spm.v:8" *)
  output done;
  (* src = "designs/spm/src/spm.v:6" *)
  input [7:0] parallel_mult;
  (* src = "designs/spm/src/spm.v:7" *)
  output [15:0] product;
  (* src = "designs/spm/src/spm.v:3" *)
  input rst;
  (* src = "designs/spm/src/spm.v:5" *)
  input serial_mult;
  (* src = "designs/spm/src/spm.v:4" *)
  input start;
  sky130_fd_sc_hd__clkinv_1 _152_ (
    .A(_128_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(_060_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor4b_1 _154_ (
    .A(_084_),
    .B(_083_),
    .C(_085_),
    .D_N(_086_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _155_ (
    .A1(_060_),
    .A2(_097_),
    .B1(_087_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _156_ (
    .A(_129_),
    .B(_098_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__mux2i_1 _157_ (
    .A0(_112_),
    .A1(_119_),
    .S(_060_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(_129_),
    .B(_099_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _159_ (
    .A0(_119_),
    .A1(_120_),
    .S(_060_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _160_ (
    .A(_129_),
    .B(_100_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__mux2i_1 _161_ (
    .A0(_120_),
    .A1(_121_),
    .S(_060_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_129_),
    .B(_101_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__mux2i_1 _163_ (
    .A0(_121_),
    .A1(_122_),
    .S(_060_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(_129_),
    .B(_102_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__mux2i_1 _165_ (
    .A0(_122_),
    .A1(_123_),
    .S(_060_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _166_ (
    .A(_129_),
    .B(_103_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__mux2i_1 _167_ (
    .A0(_123_),
    .A1(_124_),
    .S(_060_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(_129_),
    .B(_104_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__mux2i_1 _169_ (
    .A0(_124_),
    .A1(_125_),
    .S(_060_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_129_),
    .B(_105_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__mux2i_1 _171_ (
    .A0(_125_),
    .A1(_126_),
    .S(_060_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(_129_),
    .B(_106_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__mux2i_1 _173_ (
    .A0(_126_),
    .A1(_127_),
    .S(_060_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_129_),
    .B(_107_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__mux2i_1 _175_ (
    .A0(_127_),
    .A1(_113_),
    .S(_060_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_129_),
    .B(_108_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__mux2i_1 _177_ (
    .A0(_113_),
    .A1(_114_),
    .S(_060_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_129_),
    .B(_109_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__mux2i_1 _179_ (
    .A0(_114_),
    .A1(_115_),
    .S(_060_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _180_ (
    .A(_129_),
    .B(_110_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux2i_1 _181_ (
    .A0(_115_),
    .A1(_116_),
    .S(_060_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(_129_),
    .B(_111_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__mux2i_1 _183_ (
    .A0(_116_),
    .A1(_117_),
    .S(_060_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(_129_),
    .B(_088_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__mux2i_1 _185_ (
    .A0(_117_),
    .A1(_118_),
    .S(_060_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(_129_),
    .B(_089_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor3b_1 _187_ (
    .A(_060_),
    .B(_129_),
    .C_N(_118_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _188_ (
    .A1(_083_),
    .A2(_060_),
    .B1(_129_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21a_1 _189_ (
    .A1(_083_),
    .A2(_060_),
    .B1(_090_),
    .X(_039_)
  );
  sky130_fd_sc_hd__and3_1 _190_ (
    .A(_084_),
    .B(_083_),
    .C(_060_),
    .X(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(_083_),
    .A2(_060_),
    .B1(_084_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor3_1 _192_ (
    .A(_129_),
    .B(_091_),
    .C(_092_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__and4_1 _193_ (
    .A(_084_),
    .B(_083_),
    .C(_085_),
    .D(_060_),
    .X(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(_085_),
    .B(_091_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor3_1 _195_ (
    .A(_129_),
    .B(_093_),
    .C(_094_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xnor2_1 _196_ (
    .A(_086_),
    .B(_093_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_129_),
    .B(_095_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21bai_1 _198_ (
    .A1(_096_),
    .A2(_097_),
    .B1_N(_129_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _199_ (
    .A(_128_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _200_ (
    .A(_128_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _201_ (
    .A(_128_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(_128_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _203_ (
    .A(_128_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _204_ (
    .A(_128_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _205_ (
    .A(_128_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(_128_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _207_ (
    .A(_128_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _208_ (
    .A(_128_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _209_ (
    .A(_128_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _210_ (
    .A(_128_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _211_ (
    .A(_128_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _212_ (
    .A(_128_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _213_ (
    .A(_128_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _214_ (
    .A(_128_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _215_ (
    .A(_128_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _216_ (
    .A(_128_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _217_ (
    .A(_128_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _218_ (
    .A(_128_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _219_ (
    .A(_128_),
    .Y(_081_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _220_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(count[0]),
    .RESET_B(_130_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _221_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(count[1]),
    .RESET_B(_131_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _222_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(count[2]),
    .RESET_B(_132_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _223_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(count[3]),
    .RESET_B(_133_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _224_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(product[0]),
    .RESET_B(_134_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _225_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(product[1]),
    .RESET_B(_135_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _226_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(product[2]),
    .RESET_B(_136_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _227_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(product[3]),
    .RESET_B(_137_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _228_ (
    .CLK(clk),
    .D(_003_[4]),
    .Q(product[4]),
    .RESET_B(_138_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _229_ (
    .CLK(clk),
    .D(_003_[5]),
    .Q(product[5]),
    .RESET_B(_139_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _230_ (
    .CLK(clk),
    .D(_003_[6]),
    .Q(product[6]),
    .RESET_B(_140_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _231_ (
    .CLK(clk),
    .D(_003_[7]),
    .Q(product[7]),
    .RESET_B(_141_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _232_ (
    .CLK(clk),
    .D(_003_[8]),
    .Q(product[8]),
    .RESET_B(_142_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _233_ (
    .CLK(clk),
    .D(_003_[9]),
    .Q(product[9]),
    .RESET_B(_143_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _234_ (
    .CLK(clk),
    .D(_003_[10]),
    .Q(product[10]),
    .RESET_B(_144_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _235_ (
    .CLK(clk),
    .D(_003_[11]),
    .Q(product[11]),
    .RESET_B(_145_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _236_ (
    .CLK(clk),
    .D(_003_[12]),
    .Q(product[12]),
    .RESET_B(_146_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _237_ (
    .CLK(clk),
    .D(_003_[13]),
    .Q(product[13]),
    .RESET_B(_147_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _238_ (
    .CLK(clk),
    .D(_003_[14]),
    .Q(product[14]),
    .RESET_B(_148_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _239_ (
    .CLK(clk),
    .D(_003_[15]),
    .Q(product[15]),
    .RESET_B(_149_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _240_ (
    .CLK(clk),
    .D(_002_),
    .Q(done),
    .RESET_B(_150_)
  );
  (* src = "designs/spm/src/spm.v:14" *)
  sky130_fd_sc_hd__dfrtp_1 _241_ (
    .CLK(clk),
    .D(_000_),
    .Q(active),
    .RESET_B(_151_)
  );
  assign _128_ = rst;
  assign _151_ = _082_;
  assign _084_ = count[1];
  assign _083_ = count[0];
  assign _085_ = count[2];
  assign _086_ = count[3];
  assign _060_ = active;
  assign _087_ = done;
  assign _002_ = _043_;
  assign _112_ = product[0];
  assign _119_ = product[1];
  assign _129_ = start;
  assign _003_[0] = _044_;
  assign _120_ = product[2];
  assign _003_[1] = _051_;
  assign _121_ = product[3];
  assign _003_[2] = _052_;
  assign _122_ = product[4];
  assign _003_[3] = _053_;
  assign _123_ = product[5];
  assign _003_[4] = _054_;
  assign _124_ = product[6];
  assign _003_[5] = _055_;
  assign _125_ = product[7];
  assign _003_[6] = _056_;
  assign _126_ = product[8];
  assign _003_[7] = _057_;
  assign _127_ = product[9];
  assign _003_[8] = _058_;
  assign _113_ = product[10];
  assign _003_[9] = _059_;
  assign _114_ = product[11];
  assign _003_[10] = _045_;
  assign _115_ = product[12];
  assign _003_[11] = _046_;
  assign _116_ = product[13];
  assign _003_[12] = _047_;
  assign _117_ = product[14];
  assign _003_[13] = _048_;
  assign _118_ = product[15];
  assign _003_[14] = _049_;
  assign _003_[15] = _050_;
  assign _001_[0] = _039_;
  assign _001_[1] = _040_;
  assign _001_[2] = _041_;
  assign _001_[3] = _042_;
  assign _000_ = _038_;
  assign _130_ = _061_;
  assign _131_ = _062_;
  assign _132_ = _063_;
  assign _133_ = _064_;
  assign _134_ = _065_;
  assign _135_ = _066_;
  assign _136_ = _067_;
  assign _137_ = _068_;
  assign _138_ = _069_;
  assign _139_ = _070_;
  assign _140_ = _071_;
  assign _141_ = _072_;
  assign _142_ = _073_;
  assign _143_ = _074_;
  assign _144_ = _075_;
  assign _145_ = _076_;
  assign _146_ = _077_;
  assign _147_ = _078_;
  assign _148_ = _079_;
  assign _149_ = _080_;
  assign _150_ = _081_;
endmodule
